server:
  port: 9090

spring:
  cloud:
    name: resonate
    profile: dev
    config:
      server:
        git:
          uri: https://github.com/LiuJianan/FingerBoard.git
          searchPaths: Resonate/src/main/profile/dev
logging:
  level: debug
